# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(default='', max_length=32, verbose_name='用例名称')),
                ('api_desc', models.CharField(default='', max_length=255, verbose_name='用例描述')),
                ('api_url', models.CharField(default='', max_length=255, verbose_name='请求的url')),
                ('api_method', models.IntegerField(choices=[(0, 'get'), (1, 'post')], default=0, verbose_name='请求类型')),
                ('api_params', models.CharField(default={}, max_length=255, verbose_name='请求参数')),
                ('api_data', models.CharField(default={}, max_length=255, verbose_name='请求的data')),
                ('api_expect', models.CharField(default={}, max_length=5200, verbose_name='请求的预期结果')),
                ('api_report', models.TextField(default='', verbose_name='报告')),
                ('api_run_time', models.DateTimeField(null=True, verbose_name='执行时间')),
                ('api_pass_status', models.IntegerField(choices=[(0, '未通过'), (1, '已通过')], default=0, verbose_name='执行是否通过')),
                ('api_run_status', models.IntegerField(choices=[(0, '未执行'), (1, '已执行')], default=0, verbose_name='是否执行')),
            ],
        ),
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(default='', max_length=32, verbose_name='项目名称')),
                ('it_desc', models.TextField(default='', max_length=255, verbose_name='项目描述')),
                ('it_start_time', models.DateField(verbose_name='项目开始时间')),
                ('it_end_time', models.DateField(verbose_name='项目结束时间')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_report', models.TextField(default='', verbose_name='报告')),
                ('log_run_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='log日志参数时间')),
                ('log_pass_count', models.IntegerField(verbose_name='通过数量')),
                ('log_failed_count', models.IntegerField(verbose_name='失败数量')),
                ('log_error_count', models.IntegerField(verbose_name='报错数量')),
                ('log_run_count', models.IntegerField(verbose_name='执行用例总数')),
                ('log_sub_it', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.It', verbose_name='所属接口项目')),
            ],
            options={
                'ordering': ['-log_run_time'],
            },
        ),
        migrations.AddField(
            model_name='api',
            name='api_sub_it',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.It', verbose_name='所属接口的项目'),
        ),
    ]
